Loading the dataset

In [1]:
import pandas as pd 

df = pd.read_csv('job_marketdataset.csv')
df

,job_title,company,location,experience_required,salary,skills,posting_date
0,DevOps Engineer,EY,Kolkata,2.0,90316 EUR,"JavaScript, React, Node.js",2021-05-24
1,Project Manager,Apple,Remote,2.0,27 LPA approx,"Azure, Cloud, DevOps",2023-11-07
2,Product Manager,Google,Mumbai,10.0,19 LPA approx,"AWS, Docker, Kubernetes",2021-11-27
3,Cybersecurity Analyst,Microsoft,Pune,3.0,NaN,"Java, Spring Boot",2024-02-13
4,Data Scientist,Infosys,Pune,2.0,21 LPA approx,NaN,2021-04-22
...,...,...,...,...,...,...,...
15795,Project Manager,Google,Kolkata,7.0,53915 USD,"Python, SQL, Excel",2023-10-21
15796,Software Engineer,Zomato,Chennai,NaN,17 LPA approx,"Java, Spring Boot",2021-11-26
15797,Full Stack Developer,NaN,Kolkata,3.0,22 LPA,"Excel, VBA",2021-11-01
15798,DevOps Engineer,PwC,Kolkata,3.0,NaN,"AWS, Docker, Kubernetes",2024-03-25
15799,BI Developer,DataCorp,Bangalore,NaN,30 lakhs,"C++, Algorithms",2022-02-28

Performing EDA

In [2]:
df.head()

,job_title,company,location,experience_required,salary,skills,posting_date
0,DevOps Engineer,EY,Kolkata,2.0,90316 EUR,"JavaScript, React, Node.js",2021-05-24
1,Project Manager,Apple,Remote,2.0,27 LPA approx,"Azure, Cloud, DevOps",2023-11-07
2,Product Manager,Google,Mumbai,10.0,19 LPA approx,"AWS, Docker, Kubernetes",2021-11-27
3,Cybersecurity Analyst,Microsoft,Pune,3.0,NaN,"Java, Spring Boot",2024-02-13
4,Data Scientist,Infosys,Pune,2.0,21 LPA approx,NaN,2021-04-22

In [3]:
print(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 15800 entries, 0 to 15799
Data columns (total 7 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   job_title            15010 non-null  str
 1   company              15010 non-null  str
 2   location             15010 non-null  str
 3   experience_required  13074 non-null  float64
 4   salary               12532 non-null  str
 5   skills               15010 non-null  str
 6   posting_date         15010 non-null  str
dtypes: float64(1), str(6)
memory usage: 1.8 MB
None

In [4]:
print(df.isnull().sum())

job_title               790
company                 790
location                790
experience_required    2726
salary                 3268
skills                  790
posting_date            790
dtype: int64

In [5]:
df = df.dropna(subset=['job_title'])

In [6]:
df['company'] = df['company'].fillna("Unknown Company")

In [7]:
df['location'] = df['location'].fillna("Not Specified")

In [8]:
df['experience_required'] = df['experience_required'].fillna("Not Mentioned")

In [9]:
df['posting_date'] = df['posting_date'].ffill()

In [10]:
df['skills'] = df['skills'].fillna("unknown")

In [11]:
df.describe()

,job_title,company,location,experience_required,salary,skills,posting_date
count,15010,15010,15010,15010,11910,15010,15010
unique,21,25,9,8,4541,16,1201
top,Cybersecurity Analyst,Unknown Company,Kolkata,Not Mentioned,6 LPA,"Statistics, R, Python",2023-11-19
freq,792,733,1851,2608,124,1048,26

Converting Salary column which is Float into integer

In [12]:
salary_nums = df["salary"].astype(str).str.extract(r"(\d+\.?\d*)")[0]
df["salary"] = pd.to_numeric(salary_nums, errors="coerce").astype("Int64")

In [13]:
df["salary"] = df["salary"].fillna(int(df["salary"].mean().round()))

Skill Demand Analysis 

counting the skills

In [14]:
from collections import Counter
skill_series = df["skills"].dropna().str.split(",")
all_skills = [skill.strip() for sublist in skill_series for skill in sublist]
skill_counts = Counter(all_skills)

top_skills = pd.DataFrame(skill_counts.items(), columns=["skills","count"])
top_skills = top_skills.sort_values(by="count", ascending=False)

print(top_skills.head(10))

        skills  count
14      Python   4827
15         SQL   2932
12       Excel   1972
0   JavaScript   1864
26          ML   1829
24  Statistics   1048
25           R   1048
17    Power BI    993
16     Tableau    993
18  TensorFlow    989

Salary Trend Analysis

Counting average salary by roles and comparing salary and experience

In [15]:
salary_by_group = df.groupby("job_title")["salary"].mean().sort_values(ascending=False)

salary_experience = df.groupby("experience_required")["salary"].mean()

print(salary_by_group.head(10))
print(salary_experience)

job_title
Frontend Developer          42932.188467
Cybersecurity Analyst       42292.686869
Computer Vision Engineer     41270.59175
Software Engineer           41225.446429
Project Manager              41182.54858
AI Engineer                 41143.299862
BI Developer                40064.779972
Backend Developer           40035.193503
Product Manager             39794.504386
NLP Engineer                39727.755618
Name: salary, dtype: Float64
experience_required
0.0                   40223.2
1.0               40487.70232
2.0              39450.637584
3.0              38770.527778
5.0              38039.795216
7.0              39346.231456
10.0             39452.117448
Not Mentioned    39696.658359
Name: salary, dtype: Float64

Importing to SQL for data querying

In [16]:
# import mysql.connector
# import pandas as pd

# # Create connection
# conn = mysql.connector.connect(
#     host="localhost",
#     user="root",
#     password="password",
#     database="jobs"
# )

# from sqlalchemy import create_engine

# engine = create_engine("mysql+pymysql://root:password@localhost/jobs")
# df.to_sql(name='job_market', con=engine, if_exists='replace', index=False)
# print("Connected successfully!")

In [17]:
df.to_csv('cleaned_job_marketdataset.csv', index=False)